---
# Install PHP and a configurable list of PHP modules

- name: Install PHP
  yum: name=php55w state=latest
  tags:
    - php

- name: Install PHP Modules
  yum: name={{ item }} state=latest 
  with_items: php_modules
